In [1]:
from scipy.stats import kstest
from scipy import stats
import pandas as pd
import numpy as np
import seaborn as sns
%pylab inline
sns.set_theme(style="whitegrid")
from Class import taux_remplissage
from sklearn import decomposition
from functions_pca import *
from sklearn import preprocessing

Populating the interactive namespace from numpy and matplotlib


In [2]:
fakeTickets = pd.read_csv("../../lab/origin_values/faux_billets.csv", parse_dates=True) 
fakeTickets = fakeTickets.select_dtypes(exclude="bool")
fakeTickets

diagonal  height_left  height_right  margin_low  margin_up  length
0      171.81       104.86        104.95        4.52       2.89  112.83
1      171.67       103.74        103.70        4.01       2.87  113.29
2      171.83       103.76        103.76        4.40       2.88  113.84
3      171.80       103.78        103.65        3.73       3.12  113.63
4      172.05       103.70        103.75        5.04       2.27  113.55
..        ...          ...           ...         ...        ...     ...
165    172.11       104.23        104.45        5.24       3.58  111.78
166    173.01       104.59        104.31        5.04       3.05  110.91
167    172.47       104.27        104.10        4.88       3.33  110.68
168    171.82       103.97        103.88        4.73       3.55  111.87
169    171.96       104.00        103.95        5.63       3.26  110.96

[170 rows x 6 columns]

In [3]:
print(fakeTickets.shape) # (18, 6)
#nombre d'observations
n = fakeTickets.shape[0]
#nombre de variables
p = fakeTickets.shape[1]


(170, 6)


In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
Z = sc.fit_transform(fakeTickets)
Z

array([[-0.42834385,  2.6694537 ,  3.09656321, -0.13159013, -1.18987367,
         0.28163308],
       [-0.88755932, -1.09769709, -0.69125444, -0.86012554, -1.27473985,
         0.78069736],
       [-0.36274164, -1.03042654, -0.50943919, -0.30301023, -1.23230676,
         1.37740465],
       ...,
       [ 1.73652911,  0.68497248,  0.52084721,  0.38267015,  0.67718214,
        -2.05094997],
       [-0.39554274, -0.32408577, -0.1458087 ,  0.16839504,  1.61071005,
        -0.75989238],
       [ 0.06367273, -0.22317994,  0.06630909,  1.45404575,  0.38015054,
        -1.74717171]])

In [6]:
print(numpy.mean(Z,axis=0))

[ 7.69580478e-15  3.14728635e-14  3.61958829e-14  7.52339367e-16
 -1.50467873e-15 -1.37510918e-14]


In [7]:
print(numpy.std(Z,axis=0,ddof=0))

[1. 1. 1. 1. 1. 1.]


In [8]:
from sklearn.decomposition import PCA
acp = PCA(svd_solver='full')


In [9]:
coord = acp.fit_transform(Z)
coord

array([[ 2.15363875,  1.59970945,  1.78745079,  2.43346523,  0.69968952,
        -1.26770217],
       [-2.11041589, -0.52603892,  0.54256277,  0.34454951,  0.0674404 ,
        -0.54460079],
       [-1.97315242, -0.04810178,  0.85871563,  0.37481231, -0.4248861 ,
         0.08048667],
       ...,
       [ 2.06724502,  0.84560244, -0.61028227, -1.71417169,  0.1169579 ,
        -0.50433787],
       [ 0.73925685, -0.97296457, -1.35977212, -0.19173617, -0.24355701,
         0.21142914],
       [ 1.50499242, -1.07972486,  0.18888855, -1.34755225, -0.2891493 ,
        -0.06034599]])

In [10]:
print(acp.explained_variance_)

[2.86372065 1.32522178 0.85912514 0.51460481 0.27840703 0.19442354]


In [12]:
print(acp.explained_variance_.sum())

6.035502958579879


In [14]:
print(acp.explained_variance_ratio_)

[0.47447921 0.21957106 0.14234524 0.08526295 0.04612822 0.03221331]


In [26]:
eigval = acp.singular_values_**2/n
print(eigval)

[2.84687523 1.31742636 0.85407146 0.51157773 0.27676935 0.19327987]


In [27]:
print(acp.explained_variance_ratio_)

[0.47447921 0.21957106 0.14234524 0.08526295 0.04612822 0.03221331]


In [ ]:
# Cosinus. carré

In [34]:
di = numpy.sum(Z**2,axis=1)
resultCos2 = pd.DataFrame({'id':fakeTickets.index,'d_i':di})
resultCos2.sort_values(by='d_i',ascending=False)

id        d_i
166  166  20.625650
0      0  18.410598
4      4  18.039567
122  122  16.790944
39    39  15.052608
..   ...        ...
59    59   1.484454
76    76   1.435202
85    85   1.431664
98    98   0.878319
64    64   0.813929

[170 rows x 2 columns]

In [37]:
cos2 = coord**2
for j in range(p):
    cos2[:,j] = cos2[:,j]/di
    
print(pd.DataFrame({'id':fakeTickets.index,'COS2_dim_1':cos2[:,0],'COS2_dim_2':cos2[:,1]}))

      id  COS2_dim_1  COS2_dim_2
0      0    0.251929    0.139000
1      1    0.818002    0.050822
2      2    0.784862    0.000466
3      3    0.882856    0.001652
4      4    0.320145    0.009417
..   ...         ...         ...
165  165    0.800651    0.004703
166  166    0.324059    0.411824
167  167    0.498809    0.083461
168  168    0.156908    0.271800
169  169    0.421817    0.217111

[170 rows x 3 columns]


In [40]:
print(numpy.sum(cos2,axis=1))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]


In [ ]:
# CTR

In [44]:
ctr = coord**2
for j in range(p):
    ctr[:,j] = ctr[:,j]/(n*eigval[j])
    

ctrCalculation = pd.DataFrame({'id':fakeTickets.index,'CTR_dim_1':ctr[:,0],'CTR_dim_2':ctr[:,1]})

ctrCalculation

id  CTR_dim_1  CTR_dim_2
0      0   0.009584   0.011426
1      1   0.009203   0.001236
2      2   0.008045   0.000010
3      3   0.008767   0.000035
4      4   0.011933   0.000759
..   ...        ...        ...
165  165   0.012694   0.000161
166  166   0.013811   0.037927
167  167   0.008830   0.003193
168  168   0.001129   0.004227
169  169   0.004680   0.005205

[170 rows x 3 columns]

In [43]:
print(numpy.sum(ctr,axis=0))

[1. 1. 1. 1. 1. 1.]


In [45]:
base =  pd.read_csv("../../lab/origin_values/faux_billets.csv", parse_dates=True) 
base = base[['is_genuine']]
base

is_genuine
0          True
1          True
2          True
3          True
4          True
..          ...
165       False
166       False
167       False
168       False
169       False

[170 rows x 1 columns]

In [52]:
concatDim1 = pd.concat([ctrCalculation[['CTR_dim_1']], base], ignore_index=False,axis=1)
concatDim1.sort_values(by="CTR_dim_1",ascending=False).head(5)

CTR_dim_1  is_genuine
122   0.023758       False
49    0.019620        True
29    0.018089        True
112   0.017950       False
158   0.015836       False

In [51]:
concatDim2 = pd.concat([ctrCalculation[['CTR_dim_2']], base], ignore_index=False,axis=1)
concatDim2.sort_values(by="CTR_dim_2",ascending=False).head(5)

CTR_dim_2  is_genuine
5     0.039736        True
166   0.037927       False
34    0.033302        True
156   0.032264       False
70    0.031516        True